docs/AboutUs.md

Initially, placeholder names and links were placed in the `AboutUs.md` section.
As instructed in the tutorial, the `AboutUs.md` page has been updated with my details which entails my GitHub handle and my portfolio handle.

Update details section with my information

---

docs/AboutUs.md

Nancy AboutUs

---

data/database.json

Initially, the database file and data folder is empty.
A data folder and `database.json` file is created to allow us to store the information in a neat format.
Subsequently, this will allow others to add more Universities into the database and allow for new features to easily extract information from `database.json` file.
Fixes #7

[Improvement] Add information into database for Chulalongkorn University

---

data/database.json

Add more Universities into the database and allow for new features to extract information from database.json file easily.
Fixes #10

[Improvement] Add information into database for The University of Melbourne 

---

data/database.json

Add Computer Engineering related courses from the Australia National University

Add course information from Australia National University

---

data/database.json

Add Computer Engineering related courses from the Victoria University of Wellington
Fixes https://github.com/AY2425S1-CS2113-W10-2/tp/issues/16

[Improvement] Add information into database for Victoria University of Wellington

---

src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt
text-ui-test/runtest.bat
text-ui-test/runtest.sh

Fixes #9 
Include exception handling, and copy the data folder containing our JSON file from the project root into the directory where the JAR is executed, such that the relative path ./data/database.json can work in our tests.

[Feature] Add code for filtering courses and allow for reading of JSON file in runtest.bat

---

src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
text-ui-test/runtest.bat
text-ui-test/runtest.sh

Fixes #8 
Users can key in a school name and get all the course offered by that school and mapable NUS courses.

[Feature] Add code for listing school courses specified by schools

---

src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/constants/JsonKey.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/constants/Regex.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java

Some separate files will share constants, hence these constants are stored in a package and can be imported if they are needed in the code.

[Improvement] Extract constants from code

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
src/main/java/seedu/exchangecoursemapper/storage/Storage.java

Fixes #28 
Users can add a course mapping for a partner university (PU) for future reference by specifying the NUS course code, the name of the partner university (PU), and the PU course code.

[Feature] Implement add course mapping plan for a PU

---

src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java

[Improvement] Implement J-unit test into test code 

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/test/java/seedu/exchangecoursemapper/AddCoursesCommandTest.java

Fixes #34 
Add automated JUnit tests for AddCoursesCommand class

[Improvement] Implement JUnit tests for add course mapping

---

src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
text-ui-test/EXPECTED.TXT

- Instead of using startsWith() directly on the user's input, we trim the input first and use equals(). This ensures that our program only takes in valid commands from the user.
- Parser also returns a message to guide user if they have sent invalid commands.

[Improvement] Modify user input parsing in Parser class

---

src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java

Fixes #39 
Implement JUnit test for all methods in ListUniCoursesCommand class.
Each method has a test for valid inputs and a test for invalid inputs.

[Improvement] Implement JUnit tests for listing school courses

---

src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/constants/Regex.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/exception/ExchangeCourseMapperException.java
src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java

Fixes #38 
- Implement JUnit test for all methods in FilterCoursesCommand class.
- Each method has a test for valid inputs and a test for invalid inputs.

[Improvement] Implement JUnit tests for filter courses command

---

src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/exception/UnknownUniversityException.java
src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java

Fixes #45 
Add exception for when:
- University name is not provided.
- University name provided not in database.
- Data for the specific university is missing in the database.
Update JUnit test for exceptions.

[Improvement] Add more exceptions for ListUniCoursesCommand

---

src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java

[Improvement] Migrate exceptions, include assertions and logging into Filter Courses for better error handling

---

src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java

-Added logging to track user input and command execution flow.
- Introduced assertions to ensure user input is not null and input details are not empty after splitting.
- Enhanced error tracking by logging invalid commands.
- Improved visibility and error detection during runtime.
Fixes: #54

Add logging assertions to ListCommandsCommand and Parser classes

---

src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java

Fixes #56 
Add logging and assertions for better error tracking and debugging

[Improvement] Add logging and assertion for ListUniCoursesCommand

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/test/java/seedu/exchangecoursemapper/AddCoursesCommandTest.java

Fixes #58 
Add assertions and loggings for easier debugging and error handling.

[Improvement] Add assertions and loggings for AddCoursesCommand

---

src/main/java/seedu/exchangecoursemapper/command/Command.java
src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/resources/database.json

Fixes #60 
- getResourceAsStream("/database.json") ensures that the JSON file can be read as a resource inside a JAR file and IDE.

[Improvement] Add database as a resource to the JAR file

---

data/database.json
src/main/resources/database.json

[Improvement] Update the new database with emails and contacts for v2

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/courses/Course.java
src/main/java/seedu/exchangecoursemapper/storage/Storage.java

Fixes #74
To facilitate the deletion and saving of courses in the ArrayList.

[Improvement] Change storage to store course instead of string

---

src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/PersonalTrackerCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
src/main/java/seedu/exchangecoursemapper/storage/Storage.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java

Fixes #64 
Includes exception handling. Assertions and logging have not been added.

[Feature] Add code for deleting courses from the personal tracker

---

src/main/java/seedu/exchangecoursemapper/storage/Storage.java

This feature introduces a storage solution for the `myList` file, allowing course mappings to be saved and loaded in a line-by-line format in `myList.json`. Each line represents a course mapping in the format `"NUS Course | PU | PU Course"`, ensuring course data remains available across sessions.
fixes #91 & #92

[Feature] Implement save and load feature for myList

---

src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java

Fixes #102 
Fixes #101 
Changes made:
- Shorten the methods by extracting helper methods to increase 
readability and clarity
- Add Javadoc for documentation

[Improvement] Refactor code and add Javadoc to ListUniCoursesCommand

---

src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/storage/Storage.java
src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java

- Added logs to track method execution and file operations
- Implemented assertions to enforce preconditions and validate assumptions
- Enhanced error handling and maintainability
Fixes #94

[Improvement] Add logging and assertions for storage class 

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/parser/CourseValidator.java
src/test/java/seedu/exchangecoursemapper/CourseValidatorTest.java

Fixes #105 #99 #98 
Changes made: 
1. Abstract out methods that check course mappings into the CourseValidator class for better object-oriented programming (OOP) and code organisation.
2. Add assertions and loggings for better documentation and error handling. 
3. Add tests to maintain the code's defensiveness.

[Improvement] Conduct error handling for CourseValidator class

---

src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java

Fixes #85 
Implement: Assertions and Logging

[Improvement] Add logging and assertions for DeleteCoursesCommand

---

src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java

Fixes #123 
Removal of Chulalongkorn University from database requires changes in multiple tests in the FilterCoursesCommand.

[Improvement] Modify tests due to changes in database 

---

data/myList.json
src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java

88% and 83% line coverage so far 
Fixes #121

[Bugfix] Fix J-Unit code for Obtain Contacts and List schools

---

src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java

- Added logging at key execution points for better traceability.
- Implemented assertions to ensure non-null storage and mapped modules list.
- Abstracted all messages to constants for consistency and maintainability.
Fixes #126

[Improvement] Add logging and assertions to ListPersonalTrackerCommand

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/parser/CourseValidator.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java

Changes made: 
1.  Add Javadocs to CourseValidator and AddCoursesCommand classes.
2.  Extract UI-related methods from AddCoursesCommand and CourseValidator classes to the UI class for better OOP. 
Fixes #133 
Fixes #132 
Fixes #146
Fixes #145

[Improvement] Add javadocs for better documentation and extract UI methods into UI class

---

src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java

Fixes:
- FilterCourses: #143 , #141 
- DeleteCourses: #144 , #142 
Also modified ListMappedCommand, such that the list index will be shown along side the course mapping plan.

[Improvement] FilterCourses and DeleteCourses: Add JavaDocs and extract UI methods into UI class

---

docs/AboutUs.md
docs/README.md
docs/UserGuide.md
docs/team/louisjoety.md

Update ppp first draft for week 11 

---

docs/team/hzxnancy.md

Fixes #184 
The PPP documents my contributions to the project such as code contributions, developer guide contributions, review contributions etc.

Draft PPP for week 11 submission

---

docs/team/chiang-huixin.md

Fixes #182 
This PPP documents the contributions to the project like code contributions, DG, UG etc

Draft PPP for week 11 task

---

docs/team/chewycj.md

Fixes #186 
The PPP documents the contributions made to the ExchangeCourseMapper code base.

Draft PPP for week 11 task 

---

docs/UserGuide.md

[Improvement] Update UG with filtercourses and deletecourses

---

data/myList.json
src/test/java/seedu/exchangecoursemapper/CompareMappedCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java

 [Improvement] Add JUnit tests for ListPersonalTrackerCommand and CompareMappedCommand

---

src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java

- ListCommandsCommand
- ListPersonalTrackerCommand
- CompareMappedCommand

[improvement] Refactored commands to include UI class

---

docs/UserGuide.md
src/main/java/seedu/exchangecoursemapper/constants/Messages.java

[Improvement] Draft UG for v1 and v2, Add some FAQ, Add backbone of command summary

---

src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/storage/CourseFormatter.java
src/main/java/seedu/exchangecoursemapper/storage/CourseRepository.java
src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
src/main/java/seedu/exchangecoursemapper/storage/FileHandler.java
src/main/java/seedu/exchangecoursemapper/storage/Storage.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java
src/test/java/seedu/exchangecoursemapper/CompareMappedCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
src/test/java/seedu/exchangecoursemapper/StorageTest.java

- Updated `DataIntegrityChecker` to perform line-by-line validation using `isLineValid()`
- Added `validateFileIntegrity()` in `DataIntegrityChecker` to verify entire file integrity before executing repository methods
- Refactored the file integrity verification to be used right after execute() for Commands dealing with Storage:
- Enhanced those Commands to use `validateFileIntegrity()` as a pre-check in methods, preventing execution if data is corrupted
- Refactored `isLineValid()` to distinguish between parsing, validation, and unexpected errors; now logs detailed errors without terminating
- Updated tests to validate new integrity checks, error handling, and revised method flows
Brief Descriptions of Abstracted Storage Classes:
- *FileHandler*: Manages low-level file read/write …

Refactored Storage Class and added loading validation

---

docs/DeveloperGuide.md
docs/UserGuide.md

[Improvement] Update manual testing in DG for start state and CheckInformationCommands

---

docs/DeveloperGuide.md

Fixes #228 
Changes made:
- add test cases for the 3 personal tracker commands

[Improvement] Update manual guide for AddCoursesCommand, DeleteCoursesCommand and FindCoursesCommand

---

docs/DeveloperGuide.md
docs/UserGuide.md

#Fixes 232
Change the arrangement for ListUniCoursesCommand, FindCoursesCommand, HelpCommand

[Improvement] Change the order of UG and DG

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/FilterCoursesCommand.puml
src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java

[Improvement] Update order of commands in DG and UG

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update sequence in UG and DG for AddCoursesCommand

---

docs/DeveloperGuide.md
docs/UserGuide.md

Add documentaion on the location of json file and warnings regarding the corruption of the json file in UG and DG
Fixes #260

[Improvement] Add documentation regarding storage location and warnings

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/constants/Regex.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/parser/NusCourseCodeValidator.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java
src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
src/test/java/seedu/exchangecoursemapper/NusCourseCodeValidatorTest.java

Fixes #278 
- Based on the bug report, the CLI output did not match the output in the UG. This is fixed in this pull request.
- Suggestion on more detailed error messages was also implemented.

[Bug Fix] Provide more detailed guidance to user for the filter command and update documentation with newest details

---

data/myList.json
src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/exception/Exception.java
src/main/java/seedu/exchangecoursemapper/parser/NusCourseCodeValidator.java
src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java

[Bug Fix] Exception handling in Filter and delete commands

---

docs/UserGuide.md
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java
src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java

Fixes #272 
Fixes #290
Fixes #299 
Fixes #300 
Fixes #272 
Fixes #305 
Fixes #307
Fixes #311

Refactor UG and UI based on PED comments

---

data/database.json
src/main/resources/database.json
src/test/java/seedu/exchangecoursemapper/AddCoursesCommandTest.java

Removed the [NBSP] tag from the database as the courses with it  would not pass the course validator. 
Fixes #324

[BugFix] Remove [NBSP] tag from database

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/exchangecoursemapper/command/FindCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
src/main/java/seedu/exchangecoursemapper/constants/Commands.java
src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
src/main/java/seedu/exchangecoursemapper/constants/Messages.java
src/main/java/seedu/exchangecoursemapper/parser/Parser.java
src/main/java/seedu/exchangecoursemapper/ui/UI.java
src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
src/test/java/seedu/exchangecoursemapper/ParserTest.java

Fixes #269 
Fixes #271
Fixes #274 
Fixes #275 
Fixes #301 
Changes made:
- Fixes bugs based on the fix backs from PE-D
- Update JUnit test for HelpCommand
- Change the keyword of ListUniCoursesCommand from "set" to "list courses"
- Refactor code by extracting helper methods in ListUniCoursesCommand, FindCommand and HelpCommand

[Improvement] Fix bugs for V2.1 and change keyword "set" to "list courses"

---

src/main/java/seedu/exchangecoursemapper/constants/Logs.java
src/test/java/seedu/exchangecoursemapper/ParserTest.java

[BigFix] Change casing for abbreviations

---

src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
src/test/java/seedu/exchangecoursemapper/DataIntegrityCheckerTest.java

[Improvement] Add DataIntegrityCheckerTest and refactor CompareMappedCommand to accept abbreviations 

---

docs/team/chiang-huixin.md

[Improvement] Refactor and shorten PPP

---

docs/DeveloperGuide.md
docs/UserGuide.md

Fix hyperlinks for Features in UG and CourseValidator in DG

Fix hyperlinks for DG and UG

---

docs/DeveloperGuide.md

Update DG manual testing section
